# Generated by Django 4.1.7 on 2024-11-14 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFeedbackManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('direct_report_feedback', models.TextField(blank=True, null=True)),
                ('overall_review', models.TextField(blank=True, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.manager')),
            ],
        ),
        migrations.CreateModel(
            name='AdminFeedbackEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('direct_report_feedback', models.TextField(blank=True, null=True)),
                ('overall_review', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.employee')),
            ],
        ),
    ]
