# Generated by Django 4.1.7 on 2024-11-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='anonymous',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_status',
            field=models.CharField(choices=[('Acknowledged', 'Acknowledged'), ('Pending', 'Pending'), ('Responded', 'Responded')], default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
