# Generated by Django 4.1.7 on 2024-11-22 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('performance_management', '0002_performanceevaluation_manager_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userauth.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userauth.manager'),
            preserve_default=False,
        ),
    ]
