# Generated by Django 4.1.7 on 2024-11-06 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('self_rating', models.IntegerField(blank=True, help_text="Employee's self-rating (1-5)", null=True)),
                ('manager_rating', models.IntegerField(blank=True, help_text="Manager's rating (1-5)", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('review_cycle', models.CharField(choices=[('Quarterly', 'Quarterly'), ('Annually', 'Annually')], max_length=50)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Completed', 'Completed')], default='Draft', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
