# Generated by Django 4.1.7 on 2024-11-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='ManagerFeedback',
        ),
    ]
